feat: добавляет экшены
htmlonelove/liga-pug-template pull request #29
Opened 2023-06-14 12:24 UTC by yulaivanova

2023-06-15 08:42 UTC, redsmoke19 requested changes
И может быть сразу добавить доработку из соседнего ПРа где иконки раньше собирались после того как паг соберется и из за этого иногда был такой баг что что иконки не отображались. Но это наверное актуально было со старыми спрайтами а со стеками такого быть не должно ? Но тут нужно проверить и по идеии можно и стек так же в конец добавить после пага)

2023-06-15 08:42 UTC, redsmoke19 commented on .github/workflows/build.yml
> +name: Build
Там в инструкции было два варианта как эти экшены делать, и мы пришли к выводу что лучше запускать экшены не по лейблу, а по кнопке в репе, Вот актуальный код этого экшена build
```
name: Build

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Build
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: build
          folder: build
          clean: true
```

2023-06-16 09:17 UTC, yulaivanova commented on .gitignore
> -package-lock.json
поправила на [ (run: npm i,)](run: npm i)

2023-06-16 09:19 UTC, yulaivanova commented
> И может быть сразу добавить доработку из соседнего ПРа где иконки раньше собирались после того как паг соберется и из за этого иногда был такой баг что что иконки не отображались. Но это наверное актуально было со старыми спрайтами а со стеками такого быть не должно ? Но тут нужно проверить и по идеии можно и стек так же в конец добавить после пага)
> 
> А еще я вот про эту галочку в репе говорил, которую нужно поставить что бы экшены работали https://cln.sh/nGfHsLMg

ага, галочка стояла
давай отдельным пр примем ту правку

2023-08-22 09:49 UTC, redsmoke19 approved these changes

2023-08-22 12:24 UTC, merged